[features]
seeds = false
skip-lint = false

[programs.localnet]
blocklockcore = "7wizuPjcftZwL5tu9KKiEbV5KfqMWbhDLSUQuXkB8GwC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.testnet.solana.com"

[workspace]
types = "app/src/idl/"

[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.23"

