[features]
seeds = false
skip-lint = false

[programs.localnet]
#blocklockcore = "7wizuPjcftZwL5tu9KKiEbV5KfqMWbhDLSUQuXkB8GwC"
blocklockcore = "36c5ZN4fq7qm13PyEAP4X7er1ZRgzik9SyvajxDLiAQH"

[registry]
#url = "https://registry.anchor-lang.com"
url = "https://anchor.projectserum.com"

#[registry]
#url = "https://api.apr.dev"

[provider]
#cluster = "testnet"
#wallet = "/root/.config/solana/id.json"
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.testnet.solana.com"

[workspace]
types = "app/src/idl/"

[toolchain]
anchor_version = "0.30.1"
#solana_version = "2.0.10"
rust_version = "1.81.0"
solana_version = "1.18.24"

[[test.validator.clone]]
#address = "7wizuPjcftZwL5tu9KKiEbV5KfqMWbhDLSUQuXkB8GwC"
address = "36c5ZN4fq7qm13PyEAP4X7er1ZRgzik9SyvajxDLiAQH"
